version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - huggingface_cache:/root/.cache/huggingface
    environment:
      - MONGODB_URL=mongodb://mongo:27017/
      - MONGODB_DATABASE_NAME=resume_screener_db
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  huggingface_cache: